info:
  component: Config Server
spring:
  application:
    name: configserver
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          # 设置GIT URI，可是本地目录 file://e:/Workspaces/gitTest
          uri: file://d:/Program Data/my-config-repo/
          #repos:
            #- patterns: multi-repo-demo-*
            #uri: https://git.coding.net/yangsaipp/my-config-repo.git
server:
  port: 8888
management:
  context_path: /admin
  security:
    enabled: false